/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorContractSol from "./GovernorContract.sol";
export type { governorContractSol };
import type * as timeLockSol from "./TimeLock.sol";
export type { timeLockSol };
